### ISSUE TITLE
Thanks and suggestion to include ACAPS data

### ISSUE THREAD

**Issue by joachim-gassen** [lukaslehner/covid19policytrackers#1]
Hi there. Thank you very much for putting this together. Super informative. I maintain an R package pulling together some but not nearly all of the data sources that you mention (https://github.com/joachim-gassen/tidycovid19).

I wonder whether you want to include the ACAPS data on government measures (https://www.acaps.org/covid19-government-measures-dataset)? To me, it seems to be one of the most consistent and best maintained resources that are out there.

Keep up the great work!

Joachim

**Comment by lukaslehner** [comment]
Hi Joachim,

Thanks a lot for reaching out! 

Your R package and Shiny app are impressive! It's such a large number of data sources that you have already included - fascinating work!

The ACAPS data look extremely comprehensive too! I’ll put them up tomorrow.

All the best,
Lukas
